
interface Grib2SurfaceTableEntry {
    surfaceName: string;
    surfaceUnits: string;
    surfacePrintFormat: string;
}

const surface_table: Record<number, Grib2SurfaceTableEntry> = {
    1: {surfaceName: 'Ground or Water Surface', surfaceUnits: '', surfacePrintFormat: 'surface'},
    2: {surfaceName: 'Cloud Base Level', surfaceUnits: '', surfacePrintFormat: 'cloud base'},
    3: {surfaceName: 'Level of Cloud Tops', surfaceUnits: '', surfacePrintFormat: 'cloud top'},
    4: {surfaceName: 'Level of 0 \u00b0C Isotherm', surfaceUnits: '', surfacePrintFormat: '0\u00b0C isotherm'},
    5: {surfaceName: 'Level of Adiabatic Condensation Lifted from the Surface', surfaceUnits: '', surfacePrintFormat: 'level of adiabatic condensation from sfc'},
    6: {surfaceName: 'Maximum Wind Level', surfaceUnits: '', surfacePrintFormat: 'max wind'},
    7: {surfaceName: 'Tropopause', surfaceUnits: '', surfacePrintFormat: 'tropopause'},
    8: {surfaceName: 'Nominal Top of the Atmosphere', surfaceUnits: '', surfacePrintFormat: 'top of atmosphere'},
    9: {surfaceName: 'Sea Bottom', surfaceUnits: '', surfacePrintFormat: 'sea bottom'},
    10: {surfaceName: 'Entire Atmosphere', surfaceUnits: '', surfacePrintFormat: 'entire atmosphere'},
    11: {surfaceName: 'Cumulonimbus Base (CB)', surfaceUnits: 'm', surfacePrintFormat: 'cumulonimbus base'},
    12: {surfaceName: 'Cumulonimbus Top (CT)', surfaceUnits: 'm', surfacePrintFormat: 'cumulonimbus top'},
    13: {surfaceName: 'Lowest level where vertically integrated cloud cover exceeds the specified percentage (cloud base for a given percentage cloud cover)', surfaceUnits: '%', surfacePrintFormat: 'lowest level {surfaceValue}{surfaceUnits} integrated cloud cover'},
    14: {surfaceName: 'Level of free convection (LFC)', surfaceUnits: '', surfacePrintFormat: 'level of free convection'},
    15: {surfaceName: 'Convection condensation level (CCL)', surfaceUnits: '', surfacePrintFormat: 'convection condensation level'},
    16: {surfaceName: 'Level of neutral buoyancy or equilibrium (LNB)', surfaceUnits: '', surfacePrintFormat: 'level of neutral buoyancy'},
    20: {surfaceName: 'Isothermal Level', surfaceUnits: 'K', surfacePrintFormat: '{surfaceValue} {surfaceUnits} level'},
    21: {surfaceName: 'Lowest level where mass density exceeds the specified value (base for a given threshold of mass density)', surfaceUnits: 'kg/m^3', surfacePrintFormat: 'lowest level > {surfaceValue} {surfaceUnits}'},
    22: {surfaceName: 'Highest level where mass density exceeds the specified value (top for a given threshold of mass density)', surfaceUnits: 'kg/m^3', surfacePrintFormat: 'highest level > {surfaceValue} {surfaceUnits}'},
    23: {surfaceName: 'Lowest level where air concentration exceeds the specified value (base for a given threshold of air concentration', surfaceUnits: 'Bq/m^3', surfacePrintFormat: 'lowest level > {surfaceValue} {surfaceUnits}'},
    24: {surfaceName: 'Highest level where air concentration exceeds the specified value (top for a given threshold of air concentration)', surfaceUnits: 'Bq/m^3', surfacePrintFormat: 'highest level > {surfaceValue} {surfaceUnits}'},
    25: {surfaceName: 'Highest level where radar reflectivity exceeds the specified value (echo top for a given threshold of reflectivity)', surfaceUnits: 'dBZ', surfacePrintFormat: 'highest level > {surfaceValue} {surfaceUnits}'},
    26: {surfaceName: 'Convective cloud layer base', surfaceUnits: 'm', surfacePrintFormat: 'reserved'},
    27: {surfaceName: 'Convective cloud layer top', surfaceUnits: 'm', surfacePrintFormat: 'reserved'},
    30: {surfaceName: 'Specified radius from the centre of the Sun', surfaceUnits: 'm', surfacePrintFormat: 'reserved'},
    31: {surfaceName: 'Ionospheric D-region level', surfaceUnits: '', surfacePrintFormat: 'reserved'},
    32: {surfaceName: 'Ionospheric E-region level', surfaceUnits: '', surfacePrintFormat: 'reserved'},
    33: {surfaceName: 'Ionospheric F1-region level', surfaceUnits: '', surfacePrintFormat: 'reserved'},
    34: {surfaceName: 'Ionospheric F1-region level', surfaceUnits: '', surfacePrintFormat: 'reserved'},
    35: {surfaceName: 'Ionospheric F2-region level', surfaceUnits: '', surfacePrintFormat: 'reserved'},
    100: {surfaceName: 'Isobaric Surface', surfaceUnits: 'Pa', surfacePrintFormat: '{surfaceValue} {surfaceUnits}'},
    101: {surfaceName: 'Mean Sea Level', surfaceUnits: '', surfacePrintFormat: 'mean sea level'},
    102: {surfaceName: 'Specific Altitude Above Mean Sea Level', surfaceUnits: 'm', surfacePrintFormat: '{surfaceValue} {surfaceUnits} above mean sea level'},
    103: {surfaceName: 'Specified Height Level Above Ground', surfaceUnits: 'm', surfacePrintFormat: '{surfaceValue} {surfaceUnits} above ground'},
    104: {surfaceName: 'Sigma Level', surfaceUnits: '', surfacePrintFormat: '{surfaceValue} sigma level'},
    105: {surfaceName: 'Hybrid Level', surfaceUnits: '', surfacePrintFormat: '{surfaceValue} hybrid level'},
    106: {surfaceName: 'Depth Below Land Surface', surfaceUnits: 'm', surfacePrintFormat: '{surfaceValue} {surfaceUnits} underground'},
    107: {surfaceName: 'Isentropic (theta) Level', surfaceUnits: 'K', surfacePrintFormat: '{surfaceValue} {surfaceUnits} isentropic level'},
    108: {surfaceName: 'Level at Specified Pressure Difference from Ground to Level', surfaceUnits: 'Pa', surfacePrintFormat: '{surfaceValue} {surfaceUnits} above ground'},
    109: {surfaceName: 'Potential Vorticity Surface', surfaceUnits: 'Km^2/kg/s', surfacePrintFormat: 'PV={surfaceValue} ({surfaceUnits}) surface'},
    111: {surfaceName: 'Eta Level', surfaceUnits: '', surfacePrintFormat: '{surfaceValue} Eta level'},
    113: {surfaceName: 'Logarithmic Hybrid Level', surfaceUnits: '', surfacePrintFormat: '{surfaceValue} logarithmic hybrid level'},
    114: {surfaceName: 'Snow Level', surfaceUnits: 'Numeric', surfacePrintFormat: 'snow level'},
    115: {surfaceName: 'Sigma height level', surfaceUnits: '', surfacePrintFormat: '{surfaceValue} sigma height level'},
    117: {surfaceName: 'Mixed Layer Depth', surfaceUnits: 'm', surfacePrintFormat: 'mixed layer depth'},
    118: {surfaceName: 'Hybrid Height Level', surfaceUnits: '', surfacePrintFormat: '{surfaceValue} hybrid height level'},
    119: {surfaceName: 'Hybrid Pressure Level', surfaceUnits: '', surfacePrintFormat: '{surfaceValue} hybrid pressure level'},
    150: {surfaceName: 'Generalized Vertical Height Coordinate', surfaceUnits: '', surfacePrintFormat: '{surfaceValue} generalized vertical height coordinate'},
    151: {surfaceName: 'Soil level', surfaceUnits: 'Numeric', surfacePrintFormat: 'soil level {surfaceValue}'},
    152: {surfaceName: 'Sea-ice level,', surfaceUnits: 'Numeric', surfacePrintFormat: 'reserved'},
    160: {surfaceName: 'Depth Below Sea Level', surfaceUnits: 'm', surfacePrintFormat: '{surfaceValue} {surfaceUnits} below sea level'},
    161: {surfaceName: 'Depth Below Water Surface', surfaceUnits: 'm', surfacePrintFormat: '{surfaceValue} {surfaceUnits} below water surface'},
    162: {surfaceName: 'Lake or River Bottom', surfaceUnits: '', surfacePrintFormat: 'lake or river bottom'},
    163: {surfaceName: 'Bottom Of Sediment Layer', surfaceUnits: '', surfacePrintFormat: 'bottom of sediment layer'},
    164: {surfaceName: 'Bottom Of Thermally Active Sediment Layer', surfaceUnits: '', surfacePrintFormat: 'bottom of thermally active sediment layer'},
    165: {surfaceName: 'Bottom Of Sediment Layer Penetrated By Thermal Wave', surfaceUnits: '', surfacePrintFormat: 'bottom of sediment layer penetrated by thermal wave'},
    166: {surfaceName: 'Mixing Layer', surfaceUnits: '', surfacePrintFormat: 'maxing layer'},
    167: {surfaceName: 'Bottom of Root Zone', surfaceUnits: '', surfacePrintFormat: 'bottom of root zone'},
    168: {surfaceName: 'Ocean Model Level', surfaceUnits: 'Numeric', surfacePrintFormat: 'ocean model level {surfaceValue}'},
    169: {surfaceName: 'Ocean level defined by water density (sigma-theta) difference from near-surface to level', surfaceUnits: 'kg*m-3', surfacePrintFormat: 'ocean level {surfaceValue} ({surfaceUnits}) density difference to near surface'},
    170: {surfaceName: 'Ocean level defined by water potential temperature difference from near-surface to level', surfaceUnits: 'K', surfacePrintFormat: 'ocean level {surfaceValue} ({surfaceUnits}) pot. temperature difference to near surface'},
    171: {surfaceName: 'Ocean level defined by vertical eddy diffusivity difference from near-surface to level', surfaceUnits: 'm2 s-1', surfacePrintFormat: 'reserved'},
    174: {surfaceName: 'Top Surface of Ice on Sea, Lake or River', surfaceUnits: '', surfacePrintFormat: 'top surface of ice on sea, lake or river'},
    175: {surfaceName: 'Top Surface of Ice, under Snow, on Sea, Lake or River', surfaceUnits: '', surfacePrintFormat: 'top surface of ice, und snow on sea, lake or river'},
    176: {surfaceName: 'Bottom Surface (underside) Ice on Sea, Lake or River', surfaceUnits: '', surfacePrintFormat: 'bottom surface ice on sea, lake or river'},
    177: {surfaceName: 'Deep Soil (of indefinite depth)', surfaceUnits: '', surfacePrintFormat: 'deep soil'},
    179: {surfaceName: 'Top Surface of Glacier Ice and Inland Ice', surfaceUnits: '', surfacePrintFormat: 'top surface of glacier ice and inland ice'},
    180: {surfaceName: 'Deep Inland or Glacier Ice (of indefinite depth)', surfaceUnits: '', surfacePrintFormat: 'deep inland or glacier ice'},
    181: {surfaceName: 'Grid Tile Land Fraction as a Model Surface', surfaceUnits: '', surfacePrintFormat: 'grid tile land fraction as a model surface'},
    182: {surfaceName: 'Grid Tile Water Fraction as a Model Surface', surfaceUnits: '', surfacePrintFormat: 'grid tile water fraction as a model surface'},
    183: {surfaceName: 'Grid Tile Ice Fraction on Sea, Lake or River as a Model Surface', surfaceUnits: '', surfacePrintFormat: 'grid tile ice fraction on sea, lake or river as a model surface'},
    184: {surfaceName: 'Grid Tile Glacier Ice and Inland Ice Fraction as a Model Surface', surfaceUnits: '', surfacePrintFormat: 'grid tile glacier ice and inland ice fraction as a model surface'},
    200: {surfaceName: 'Entire atmosphere (considered as a single layer)', surfaceUnits: '', surfacePrintFormat: 'entire atmosphere (considered as a single layer)'},
    201: {surfaceName: 'Entire ocean (considered as a single layer)', surfaceUnits: '', surfacePrintFormat: 'entire ocean (considered as a single layer)'},
    204: {surfaceName: 'Highest tropospheric freezing level', surfaceUnits: '', surfacePrintFormat: 'highest tropospheric freezing level'},
    206: {surfaceName: 'Grid scale cloud bottom level', surfaceUnits: '', surfacePrintFormat: 'grid scale cloud bottom level'},
    207: {surfaceName: 'Grid scale cloud top level', surfaceUnits: '', surfacePrintFormat: 'grid scale cloud top level'},
    209: {surfaceName: 'Boundary layer cloud bottom level', surfaceUnits: '', surfacePrintFormat: 'boundary layer cloud bottom level'},
    210: {surfaceName: 'Boundary layer cloud top level', surfaceUnits: '', surfacePrintFormat: 'boundary layer cloud top level'},
    211: {surfaceName: 'Boundary layer cloud layer', surfaceUnits: '', surfacePrintFormat: 'boundary layer cloud layer'},
    212: {surfaceName: 'Low cloud bottom level', surfaceUnits: '', surfacePrintFormat: 'low cloud bottom level'},
    213: {surfaceName: 'Low cloud top level', surfaceUnits: '', surfacePrintFormat: 'low cloud top level'},
    214: {surfaceName: 'Low cloud layer', surfaceUnits: '', surfacePrintFormat: 'low cloud layer'},
    215: {surfaceName: 'Cloud ceiling', surfaceUnits: '', surfacePrintFormat: 'cloud ceiling'},
    216: {surfaceName: 'Effective Layer Top Level', surfaceUnits: 'm', surfacePrintFormat: 'effective layer top level {surfaceValue}m'},
    217: {surfaceName: 'Effective Layer Bottom Level', surfaceUnits: 'm', surfacePrintFormat: 'effective layer bottom level {surfaceValue}m'},
    218: {surfaceName: 'Effective Layer', surfaceUnits: 'm', surfacePrintFormat: 'effective layer {surfaceValue}m'},
    220: {surfaceName: 'Planetary Boundary Layer', surfaceUnits: '', surfacePrintFormat: 'planetary boundary layer'},
    221: {surfaceName: 'Layer Between Two Hybrid Levels', surfaceUnits: '', surfacePrintFormat: 'layer between two hybrid levels'},
    222: {surfaceName: 'Middle cloud bottom level', surfaceUnits: '', surfacePrintFormat: 'middle cloud bottom level'},
    223: {surfaceName: 'Middle cloud top level', surfaceUnits: '', surfacePrintFormat: 'middle cloud top level'},
    224: {surfaceName: 'Middle cloud layer', surfaceUnits: '', surfacePrintFormat: 'middle cloud layer'},
    232: {surfaceName: 'High cloud bottom level', surfaceUnits: '', surfacePrintFormat: 'high cloud bottom level'},
    233: {surfaceName: 'High cloud top level', surfaceUnits: '', surfacePrintFormat: 'high cloud top level'},
    234: {surfaceName: 'High cloud layer', surfaceUnits: '', surfacePrintFormat: 'high cloud layer'},
    235: {surfaceName: 'Ocean Isotherm Level (1/10 \u00b0 C)', surfaceUnits: '', surfacePrintFormat: '{surfaceValue}C ocean isotherm'},
    236: {surfaceName: 'Layer between two depths below ocean surface', surfaceUnits: '', surfacePrintFormat: 'layer between two depths below ocean surface'},
    237: {surfaceName: 'Bottom of Ocean Mixed Layer', surfaceUnits: 'm', surfacePrintFormat: 'bottom of ocean mixed layer'},
    238: {surfaceName: 'Bottom of Ocean Isothermal Layer', surfaceUnits: 'm', surfacePrintFormat: 'bottom of ocean isothermal layer'},
    239: {surfaceName: 'Layer Ocean Surface and 26C Ocean Isothermal Level', surfaceUnits: '', surfacePrintFormat: 'layer ocean surface and 26C ocean isothermal level'},
    240: {surfaceName: 'Ocean Mixed Layer', surfaceUnits: '', surfacePrintFormat: 'ocean mixed layer'},
    241: {surfaceName: 'Ordered Sequence of Data', surfaceUnits: '', surfacePrintFormat: '{surfaceValue} in sequence'},
    242: {surfaceName: 'Convective cloud bottom level', surfaceUnits: '', surfacePrintFormat: 'convective cloud bottom level'},
    243: {surfaceName: 'Convective cloud top level', surfaceUnits: '', surfacePrintFormat: 'convective cloud top level'},
    244: {surfaceName: 'Convective cloud layer', surfaceUnits: '', surfacePrintFormat: 'convective cloud layer'},
    245: {surfaceName: 'Lowest level of the wet bulb zero', surfaceUnits: '', surfacePrintFormat: 'lowest level of the wet bulb zero'},
    246: {surfaceName: 'Maximum equivalent potential temperature level', surfaceUnits: '', surfacePrintFormat: 'maximum equivalent potential temperature level'},
    247: {surfaceName: 'Equilibrium level', surfaceUnits: '', surfacePrintFormat: 'equilibrium level'},
    248: {surfaceName: 'Shallow convective cloud bottom level', surfaceUnits: '', surfacePrintFormat: 'shallow convective cloud bottom level'},
    249: {surfaceName: 'Shallow convective cloud top level', surfaceUnits: '', surfacePrintFormat: 'shallow convective cloud top level'},
    251: {surfaceName: 'Deep convective cloud bottom level', surfaceUnits: '', surfacePrintFormat: 'deep convective cloud bottom level'},
    252: {surfaceName: 'Deep convective cloud top level', surfaceUnits: '', surfacePrintFormat: 'deep convective cloud top level'},
    253: {surfaceName: 'Lowest bottom level of supercooled liquid water layer', surfaceUnits: '', surfacePrintFormat: 'lowest bottom level of supercooled liquid water layer'},
    254: {surfaceName: 'Highest top level of supercooled liquid water layer', surfaceUnits: '', surfacePrintFormat: 'highest top level of supercooled liquid water layer'}
}

function lookupGrib2Surface(surface_number: number) {
    const unknown_surface = {surfaceName: 'unknown', surfaceUnits: 'unknown'} as Grib2SurfaceTableEntry;

    const surface = surface_table[surface_number];
    if (surface === undefined) {
        return unknown_surface;
    }

    return surface;
}

export {lookupGrib2Surface};
export type {Grib2SurfaceTableEntry};