
interface Grib2SurfaceTableEntry {
    surfaceName: string;
    surfaceUnits: string;
}

const surface_table: Record<number, Grib2SurfaceTableEntry> = {
    1: {surfaceName: 'Ground or Water Surface', surfaceUnits: ''},
    2: {surfaceName: 'Cloud Base Level', surfaceUnits: ''},
    3: {surfaceName: 'Level of Cloud Tops', surfaceUnits: ''},
    4: {surfaceName: 'Level of 0o C Isotherm', surfaceUnits: ''},
    5: {surfaceName: 'Level of Adiabatic Condensation Lifted from the Surface', surfaceUnits: ''},
    6: {surfaceName: 'Maximum Wind Level', surfaceUnits: ''},
    7: {surfaceName: 'Tropopause', surfaceUnits: ''},
    8: {surfaceName: 'Nominal Top of the Atmosphere', surfaceUnits: ''},
    9: {surfaceName: 'Sea Bottom', surfaceUnits: ''},
    10: {surfaceName: 'Entire Atmosphere', surfaceUnits: ''},
    11: {surfaceName: 'Cumulonimbus Base (CB)', surfaceUnits: 'm'},
    12: {surfaceName: 'Cumulonimbus Top (CT)', surfaceUnits: 'm'},
    13: {surfaceName: 'Lowest level where vertically integrated cloud cover exceeds the specified percentage (cloud base for a given percentage cloud cover)', surfaceUnits: '%'},
    14: {surfaceName: 'Level of free convection (LFC)', surfaceUnits: ''},
    15: {surfaceName: 'Convection condensation level (CCL)', surfaceUnits: ''},
    16: {surfaceName: 'Level of neutral buoyancy or equilibrium (LNB)', surfaceUnits: ''},
    20: {surfaceName: 'Isothermal Level', surfaceUnits: 'K'},
    21: {surfaceName: 'Lowest level where mass density exceeds the specified value (base for a given threshold of mass density)', surfaceUnits: 'kg m-3'},
    22: {surfaceName: 'Highest level where mass density exceeds the specified value (top for a given threshold of mass density)', surfaceUnits: 'kg m-3'},
    23: {surfaceName: 'Lowest level where air concentration exceeds the specified value (base for a given threshold of air concentration', surfaceUnits: 'Bq m-3'},
    24: {surfaceName: 'Highest level where air concentration exceeds the specified value (top for a given threshold of air concentration)', surfaceUnits: 'Bq m-3'},
    25: {surfaceName: 'Highest level where radar reflectivity exceeds the specified value (echo top for a given threshold of reflectivity)', surfaceUnits: 'dBZ'},
    26: {surfaceName: 'Convective cloud layer base', surfaceUnits: 'm'},
    27: {surfaceName: 'Convective cloud layer top', surfaceUnits: 'm'},
    30: {surfaceName: 'Specified radius from the centre of the Sun', surfaceUnits: 'm'},
    31: {surfaceName: 'Ionospheric D-region level', surfaceUnits: ''},
    32: {surfaceName: 'Ionospheric E-region level', surfaceUnits: ''},
    33: {surfaceName: 'Ionospheric F1-region level', surfaceUnits: ''},
    34: {surfaceName: 'Ionospheric F1-region level', surfaceUnits: ''},
    35: {surfaceName: 'Ionospheric F2-region level', surfaceUnits: ''},
    100: {surfaceName: 'Isobaric Surface', surfaceUnits: 'Pa'},
    101: {surfaceName: 'Mean Sea Level', surfaceUnits: ''},
    102: {surfaceName: 'Specific Altitude Above Mean Sea Level', surfaceUnits: 'm'},
    103: {surfaceName: 'Specified Height Level Above Ground', surfaceUnits: 'm'},
    104: {surfaceName: 'Sigma Level', surfaceUnits: ''},
    105: {surfaceName: 'Hybrid Level', surfaceUnits: ''},
    106: {surfaceName: 'Depth Below Land Surface', surfaceUnits: 'm'},
    107: {surfaceName: 'Isentropic (theta) Level', surfaceUnits: 'K'},
    108: {surfaceName: 'Level at Specified Pressure Difference from Ground to Level', surfaceUnits: 'Pa'},
    109: {surfaceName: 'Potential Vorticity Surface', surfaceUnits: 'K m2 kg-1 s-1'},
    111: {surfaceName: 'Eta Level', surfaceUnits: ''},
    113: {surfaceName: 'Logarithmic Hybrid Level', surfaceUnits: ''},
    114: {surfaceName: 'Snow Level', surfaceUnits: 'Numeric'},
    115: {surfaceName: 'Sigma height level (see Note 4)', surfaceUnits: ''},
    117: {surfaceName: 'Mixed Layer Depth', surfaceUnits: 'm'},
    118: {surfaceName: 'Hybrid Height Level', surfaceUnits: ''},
    119: {surfaceName: 'Hybrid Pressure Level', surfaceUnits: ''},
    150: {surfaceName: 'Generalized Vertical Height Coordinate (see Note 4)', surfaceUnits: ''},
    151: {surfaceName: 'Soil level (See Note 5)', surfaceUnits: 'Numeric'},
    152: {surfaceName: 'Sea-ice level,(see Note 8)', surfaceUnits: 'Numeric'},
    160: {surfaceName: 'Depth Below Sea Level', surfaceUnits: 'm'},
    161: {surfaceName: 'Depth Below Water Surface', surfaceUnits: 'm'},
    162: {surfaceName: 'Lake or River Bottom', surfaceUnits: ''},
    163: {surfaceName: 'Bottom Of Sediment Layer', surfaceUnits: ''},
    164: {surfaceName: 'Bottom Of Thermally Active Sediment Layer', surfaceUnits: ''},
    165: {surfaceName: 'Bottom Of Sediment Layer Penetrated By Thermal Wave', surfaceUnits: ''},
    166: {surfaceName: 'Mixing Layer', surfaceUnits: ''},
    167: {surfaceName: 'Bottom of Root Zone', surfaceUnits: ''},
    168: {surfaceName: 'Ocean Model Level', surfaceUnits: 'Numeric'},
    169: {surfaceName: 'Ocean level defined by water density (sigma-theta) difference from near-surface to level (see Note 7)', surfaceUnits: 'kg m-3'},
    170: {surfaceName: 'Ocean level defined by water potential temperature difference from near-surface to level (see Note 7)', surfaceUnits: 'K'},
    171: {surfaceName: 'Ocean level defined by vertical eddy diffusivity difference from near-surface to level,(see Note 7)', surfaceUnits: 'm2 s-1'},
    174: {surfaceName: 'Top Surface of Ice on Sea, Lake or River', surfaceUnits: ''},
    175: {surfaceName: 'Top Surface of Ice, under Snow, on Sea, Lake or River', surfaceUnits: ''},
    176: {surfaceName: 'Bottom Surface (underside) Ice on Sea, Lake or River', surfaceUnits: ''},
    177: {surfaceName: 'Deep Soil (of indefinite depth)', surfaceUnits: ''},
    179: {surfaceName: 'Top Surface of Glacier Ice and Inland Ice', surfaceUnits: ''},
    180: {surfaceName: 'Deep Inland or Glacier Ice (of indefinite depth)', surfaceUnits: ''},
    181: {surfaceName: 'Grid Tile Land Fraction as a Model Surface', surfaceUnits: ''},
    182: {surfaceName: 'Grid Tile Water Fraction as a Model Surface', surfaceUnits: ''},
    183: {surfaceName: 'Grid Tile Ice Fraction on Sea, Lake or River as a Model Surface', surfaceUnits: ''},
    184: {surfaceName: 'Grid Tile Glacier Ice and Inland Ice Fraction as a Model Surface', surfaceUnits: ''},
    200: {surfaceName: 'Entire atmosphere (considered as a single layer)', surfaceUnits: ''},
    201: {surfaceName: 'Entire ocean (considered as a single layer)', surfaceUnits: ''},
    204: {surfaceName: 'Highest tropospheric freezing level', surfaceUnits: ''},
    206: {surfaceName: 'Grid scale cloud bottom level', surfaceUnits: ''},
    207: {surfaceName: 'Grid scale cloud top level', surfaceUnits: ''},
    209: {surfaceName: 'Boundary layer cloud bottom level', surfaceUnits: ''},
    210: {surfaceName: 'Boundary layer cloud top level', surfaceUnits: ''},
    211: {surfaceName: 'Boundary layer cloud layer', surfaceUnits: ''},
    212: {surfaceName: 'Low cloud bottom level', surfaceUnits: ''},
    213: {surfaceName: 'Low cloud top level', surfaceUnits: ''},
    214: {surfaceName: 'Low cloud layer', surfaceUnits: ''},
    215: {surfaceName: 'Cloud ceiling', surfaceUnits: ''},
    216: {surfaceName: 'Effective Layer Top Level', surfaceUnits: 'm'},
    217: {surfaceName: 'Effective Layer Bottom Level', surfaceUnits: 'm'},
    218: {surfaceName: 'Effective Layer', surfaceUnits: 'm'},
    220: {surfaceName: 'Planetary Boundary Layer', surfaceUnits: ''},
    221: {surfaceName: 'Layer Between Two Hybrid Levels', surfaceUnits: ''},
    222: {surfaceName: 'Middle cloud bottom level', surfaceUnits: ''},
    223: {surfaceName: 'Middle cloud top level', surfaceUnits: ''},
    224: {surfaceName: 'Middle cloud layer', surfaceUnits: ''},
    232: {surfaceName: 'High cloud bottom level', surfaceUnits: ''},
    233: {surfaceName: 'High cloud top level', surfaceUnits: ''},
    234: {surfaceName: 'High cloud layer', surfaceUnits: ''},
    235: {surfaceName: 'Ocean Isotherm Level (1/10 ° C)', surfaceUnits: ''},
    236: {surfaceName: 'Layer between two depths below ocean surface', surfaceUnits: ''},
    237: {surfaceName: 'Bottom of Ocean Mixed Layer', surfaceUnits: 'm'},
    238: {surfaceName: 'Bottom of Ocean Isothermal Layer', surfaceUnits: 'm'},
    239: {surfaceName: 'Layer Ocean Surface and 26C Ocean Isothermal Level', surfaceUnits: ''},
    240: {surfaceName: 'Ocean Mixed Layer', surfaceUnits: ''},
    241: {surfaceName: 'Ordered Sequence of Data', surfaceUnits: ''},
    242: {surfaceName: 'Convective cloud bottom level', surfaceUnits: ''},
    243: {surfaceName: 'Convective cloud top level', surfaceUnits: ''},
    244: {surfaceName: 'Convective cloud layer', surfaceUnits: ''},
    245: {surfaceName: 'Lowest level of the wet bulb zero', surfaceUnits: ''},
    246: {surfaceName: 'Maximum equivalent potential temperature level', surfaceUnits: ''},
    247: {surfaceName: 'Equilibrium level', surfaceUnits: ''},
    248: {surfaceName: 'Shallow convective cloud bottom level', surfaceUnits: ''},
    249: {surfaceName: 'Shallow convective cloud top level', surfaceUnits: ''},
    251: {surfaceName: 'Deep convective cloud bottom level', surfaceUnits: ''},
    252: {surfaceName: 'Deep convective cloud top level', surfaceUnits: ''},
    253: {surfaceName: 'Lowest bottom level of supercooled liquid water layer', surfaceUnits: ''},
    254: {surfaceName: 'Highest top level of supercooled liquid water layer', surfaceUnits: ''},
}

function lookupGrib2Surface(surface_number: number) {
    const unknown_surface = {surfaceName: 'unknown', surfaceUnits: 'unknown'} as Grib2SurfaceTableEntry;

    const surface = surface_table[surface_number];
    if (surface === undefined) {
        return unknown_surface;
    }

    return surface;
}

export {lookupGrib2Surface};
export type {Grib2SurfaceTableEntry};